// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: '${dotenv.get('APIKEY_WEB')}',
    appId: '1:841631435830:web:3c963023d887c5065d5c97',
    messagingSenderId: '841631435830',
    projectId: 'fir-bloc-90d8b',
    authDomain: 'fir-bloc-90d8b.firebaseapp.com',
    storageBucket: 'fir-bloc-90d8b.appspot.com',
    measurementId: 'G-JL68QEXHM6',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: '${dotenv.get('APIKEY_ANDROID')}',
    appId: '1:841631435830:android:e75112a92b67fdd95d5c97',
    messagingSenderId: '841631435830',
    projectId: 'fir-bloc-90d8b',
    storageBucket: 'fir-bloc-90d8b.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: '${dotenv.get('APIKEY_IOS')}',
    appId: '1:841631435830:ios:088373fd8ba26d555d5c97',
    messagingSenderId: '841631435830',
    projectId: 'fir-bloc-90d8b',
    storageBucket: 'fir-bloc-90d8b.appspot.com',
    iosBundleId: 'com.example.blocFirebase',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: '${dotenv.get('APIKEY_MAC')}',
    appId: '1:841631435830:ios:088373fd8ba26d555d5c97',
    messagingSenderId: '841631435830',
    projectId: 'fir-bloc-90d8b',
    storageBucket: 'fir-bloc-90d8b.appspot.com',
    iosBundleId: 'com.example.blocFirebase',
  );

  static FirebaseOptions windows = FirebaseOptions(
    apiKey: '${dotenv.get('APIKEY_WIND')}',
    appId: '1:841631435830:web:f4ff13e31b05c0785d5c97',
    messagingSenderId: '841631435830',
    projectId: 'fir-bloc-90d8b',
    authDomain: 'fir-bloc-90d8b.firebaseapp.com',
    storageBucket: 'fir-bloc-90d8b.appspot.com',
    measurementId: 'G-PNPMV0CF24',
  );
}
